begin;
select plan(47);
select has_type('public','ai_task_status','AI task lifecycle exists');
select has_type('public','ai_task_audience','AI audience boundary exists');
select has_type('public','support_case_status','support case lifecycle exists');
select has_table('public','ai_provider_settings','AI provider settings exist');
select has_table('public','ai_prompt_versions','versioned AI prompts exist');
select has_table('public','ai_tasks','AI audit tasks exist');
select has_table('public','patient_ai_messages','safe patient AI messages exist');
select has_table('public','feature_flags','feature flags exist');
select has_table('public','platform_usage_limits','usage limits exist');
select has_table('public','api_rate_limits','rate-limit buckets exist');
select has_table('public','ai_usage_daily','AI usage summaries exist');
select has_table('public','notification_deliveries','notification deliveries exist');
select has_table('public','notification_devices','notification devices exist');
select has_table('public','support_cases','support cases exist');
select has_table('public','moderation_actions','moderation actions exist');
select has_function('public','rotate_ai_provider_secret','AI key rotation exists');
select has_function('public','ai_provider_secret','AI secret reader exists');
select has_function('public','consume_api_limit','rate limiting exists');
select has_function('public','prepare_ai_task','AI task preparation exists');
select has_function('public','complete_ai_task','AI task completion exists');
select has_function('public','review_ai_task','AI field review exists');
select has_function('public','apply_reviewed_ai_task','AI review and clinical application are atomic');
select has_function('public','ai_daily_limit','configured subscription-aware AI limits exist');
select has_function('public','set_feature_flag','feature flag control exists');
select has_function('public','set_platform_usage_limit','usage limit control exists');
select has_function('public','super_admin_ai_task_snapshot','audited AI inspection exists');
select has_function('public','register_notification_device','device registration exists');
select has_function('public','claim_notification_batch','notification queue claim exists');
select has_function('public','finish_notification_delivery','notification result handling exists');
select ok(not has_table_privilege('authenticated','public.ai_tasks','INSERT'),'clients cannot forge AI audit tasks');
select ok(not has_table_privilege('authenticated','public.ai_tasks','UPDATE'),'clients cannot overwrite raw output');
select ok(not has_table_privilege('authenticated','public.ai_provider_settings','UPDATE'),'clients cannot write provider metadata directly');
select ok(not has_table_privilege('authenticated','public.api_rate_limits','SELECT'),'clients cannot inspect abuse-control buckets');
select ok(not has_function_privilege('authenticated','public.ai_provider_secret(text)','EXECUTE'),'clients cannot read provider secrets');
select ok(not has_function_privilege('authenticated','public.rotate_ai_provider_secret(uuid,text,text,text)','EXECUTE'),'clients cannot call secret rotation RPC');
select ok(has_function_privilege('authenticated','public.prepare_ai_task(text,uuid,uuid,uuid,text,text)','EXECUTE'),'authenticated users may call guarded AI preparation');
select ok(not has_function_privilege('authenticated','public.review_ai_task(uuid,jsonb,jsonb,text)','EXECUTE'),'clients cannot bypass atomic AI application');
select ok(has_function_privilege('authenticated','public.apply_reviewed_ai_task(uuid,jsonb,jsonb,text)','EXECUTE'),'dentists may call atomic guarded field review');
select col_is_null('public','ai_tasks','raw_output','raw provider output is nullable until server completion');
select col_is_null('public','ai_tasks','safe_output','patient-safe output is separate');
select col_is_null('public','ai_tasks','final_output','dentist-reviewed output is separate');
select is((select enabled from public.feature_flags where flag_key='experimental_xray_ai'),false,'experimental X-ray AI defaults off');
select is((select count(*)::integer from public.ai_prompt_versions),8,'every supported AI task has a versioned prompt');
select has_trigger('public','ai_provider_settings','ai_provider_settings_touch_updated_at','provider settings are timestamped');
select has_trigger('public','notification_deliveries','notification_deliveries_touch_updated_at','notification retries are timestamped');
select has_trigger('public','support_cases','support_cases_touch_updated_at','case updates are timestamped');
select has_trigger('public','ai_tasks','ai_tasks_enforce_feature_flags','AI release flags are database-enforced');
select * from finish();
rollback;
