begin;
select plan(61);
select has_type('public','payment_provider','bKash and Nagad provider enum exists');
select has_type('public','payment_state','payment lifecycle exists');
select has_type('public','invoice_state','invoice lifecycle exists');
select has_type('public','stock_movement_type','stock movement enum exists');
select has_type('public','purchase_order_state','purchase order lifecycle exists');
select has_type('public','lab_case_state','lab workflow exists');
select has_type('public','subscription_state','subscription lifecycle exists');
select has_type('public','subscription_tier','subscription tiers exist');
select has_table('public','platform_commission_rules','commission rules exist');select has_table('public','invoices','invoices exist');select has_table('public','invoice_items','invoice items exist');
select has_table('public','payment_transactions','payment transactions exist');select has_table('public','payment_webhook_events','payment webhook events exist');select has_table('public','refunds','refunds exist');
select has_table('public','expenses','expenses exist');select has_table('public','clinic_ledger_entries','clinic ledger exists');select has_table('public','clinic_payouts','clinic payouts exist');
select has_table('public','suppliers','suppliers exist');select has_table('public','inventory_items','inventory items exist');select has_table('public','inventory_lots','inventory lots exist');select has_table('public','stock_movements','stock movements exist');
select has_table('public','purchase_orders','purchase orders exist');select has_table('public','purchase_order_items','purchase order items exist');select has_table('public','lab_vendors','lab vendors exist');select has_table('public','lab_cases','lab cases exist');
select has_table('public','lab_case_events','lab case events exist');select has_table('public','lab_case_attachments','lab attachments exist');select has_table('public','subscription_plans','subscription plans exist');select has_table('public','user_subscriptions','user subscriptions exist');select has_table('public','subscription_webhook_events','subscription events exist');
select has_function('public','active_commission_rate','commission lookup exists');select has_function('public','validate_subscription_scope','subscription validation exists');select has_function('public','prepare_payment_checkout','checkout preparation exists');select has_function('public','set_payment_checkout_result','checkout result writer exists');
select has_function('public','prepare_refund','refund preparation exists');select has_function('public','apply_refund_result','refund result writer exists');select has_function('public','create_invoice','invoice creation exists');select has_function('public','record_expense','expense recording exists');
select has_function('public','create_inventory_item','inventory item creation exists');select has_function('public','post_stock_movement','stock movement posting exists');select has_function('public','create_inventory_lot','inventory lot creation exists');select has_function('public','create_lab_case','lab case creation exists');
select has_function('public','advance_lab_case','lab workflow transition exists');select has_function('public','has_entitlement','entitlement lookup exists');select has_function('public','set_subscription_plan','plan configuration exists');select has_function('public','set_commission_rate','commission configuration exists');
select has_function('public','apply_payment_event','payment event processing exists');select has_function('public','apply_subscription_event','subscription event processing exists');select has_function('public','clinic_finance_summary','finance summary exists');
select has_function('public','create_supplier','supplier creation exists');select has_function('public','create_purchase_order','purchase order creation exists');select has_function('public','receive_purchase_order_item','purchase receiving exists');select has_function('public','create_lab_vendor','lab vendor creation exists');select has_function('public','request_clinic_payout','payout request exists');
select is((select public from storage.buckets where id='lab-attachments'),false,'lab attachments bucket is private');
select ok(not has_table_privilege('authenticated','public.payment_transactions','INSERT'),'clients cannot insert payments');
select ok(not has_table_privilege('authenticated','public.clinic_ledger_entries','INSERT'),'clients cannot forge ledger entries');
select ok(not has_table_privilege('authenticated','public.inventory_lots','UPDATE'),'clients cannot bypass atomic stock RPC');
select ok(not has_function_privilege('authenticated','public.apply_payment_event(public.payment_provider,text,uuid,text,public.payment_state,jsonb,text)','EXECUTE'),'clients cannot apply payment webhooks');
select ok(has_function_privilege('authenticated','public.prepare_payment_checkout(uuid,public.payment_provider,text)','EXECUTE'),'patients may call guarded checkout preparation');
select has_trigger('public','user_subscriptions','subscriptions_validate_scope','subscription scope is trigger-enforced');
select * from finish();
rollback;
