begin;
select plan(61);
select has_type('public','payment_provider','bKash and Nagad provider enum exists');
select has_type('public','payment_state','payment lifecycle exists');
select has_type('public','invoice_state','invoice lifecycle exists');
select has_type('public','stock_movement_type','stock movement enum exists');
select has_type('public','purchase_order_state','purchase order lifecycle exists');
select has_type('public','lab_case_state','lab workflow exists');
select has_type('public','subscription_state','subscription lifecycle exists');
select has_type('public','subscription_tier','subscription tiers exist');
select has_table('public','platform_commission_rules');select has_table('public','invoices');select has_table('public','invoice_items');
select has_table('public','payment_transactions');select has_table('public','payment_webhook_events');select has_table('public','refunds');
select has_table('public','expenses');select has_table('public','clinic_ledger_entries');select has_table('public','clinic_payouts');
select has_table('public','suppliers');select has_table('public','inventory_items');select has_table('public','inventory_lots');select has_table('public','stock_movements');
select has_table('public','purchase_orders');select has_table('public','purchase_order_items');select has_table('public','lab_vendors');select has_table('public','lab_cases');
select has_table('public','lab_case_events');select has_table('public','lab_case_attachments');select has_table('public','subscription_plans');select has_table('public','user_subscriptions');select has_table('public','subscription_webhook_events');
select has_function('public','active_commission_rate');select has_function('public','validate_subscription_scope');select has_function('public','prepare_payment_checkout');select has_function('public','set_payment_checkout_result');
select has_function('public','prepare_refund');select has_function('public','apply_refund_result');select has_function('public','create_invoice');select has_function('public','record_expense');
select has_function('public','create_inventory_item');select has_function('public','post_stock_movement');select has_function('public','create_inventory_lot');select has_function('public','create_lab_case');
select has_function('public','advance_lab_case');select has_function('public','has_entitlement');select has_function('public','set_subscription_plan');select has_function('public','set_commission_rate');
select has_function('public','apply_payment_event');select has_function('public','apply_subscription_event');select has_function('public','clinic_finance_summary');
select has_function('public','create_supplier');select has_function('public','create_purchase_order');select has_function('public','receive_purchase_order_item');select has_function('public','create_lab_vendor');select has_function('public','request_clinic_payout');
select results_eq($$select public from storage.buckets where id='lab-attachments'$$,$$values(false)$$,'lab attachments bucket is private');
select ok(not has_table_privilege('authenticated','public.payment_transactions','INSERT'),'clients cannot insert payments');
select ok(not has_table_privilege('authenticated','public.clinic_ledger_entries','INSERT'),'clients cannot forge ledger entries');
select ok(not has_table_privilege('authenticated','public.inventory_lots','UPDATE'),'clients cannot bypass atomic stock RPC');
select ok(not has_function_privilege('authenticated','public.apply_payment_event(public.payment_provider,text,uuid,text,public.payment_state,jsonb,text)','EXECUTE'),'clients cannot apply payment webhooks');
select ok(has_function_privilege('authenticated','public.prepare_payment_checkout(uuid,public.payment_provider,text)','EXECUTE'),'patients may call guarded checkout preparation');
select has_trigger('public','user_subscriptions','subscriptions_validate_scope','subscription scope is trigger-enforced');
select * from finish();
rollback;
