project_id = "amar-dentist"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["amardentist://auth/callback", "amardentist://reset-password", "http://localhost:8081/auth/callback", "http://localhost:8081/reset-password", "http://localhost:5173/auth/callback"]
enable_signup = true
minimum_password_length = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[storage]
enabled = true
file_size_limit = "20MiB"
