// THESIS: Secrets are handled like sealed instruments, not ordinary settings. OWN-WORLD: white ledger panels, ink controls, mint proof states. STORY: inspect provider status, rotate without reveal, tune flags and quotas. FIRST VIEWPORT: masked status and write-only key action. FORM: security console.
import { Button } from '@heroui/react/button'
import { Bot, CheckCircle2, Gauge, KeyRound, ShieldCheck, ToggleLeft, ToggleRight } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { supabase } from '../lib/supabase'

type Provider={provider:string;model:string;key_hint:string;enabled:boolean;configured_at:string|null}
type Flag={flag_key:string;description:string;enabled:boolean;audience:string}
type Limit={limit_key:string;description:string;free_value:number;paid_value:number}
const previewProvider:Provider={provider:'openai',model:'gpt-5-mini',key_hint:'Not configured',enabled:false,configured_at:null}
const connectedProvider:Provider={provider:'openai',model:'',key_hint:'Loading live status',enabled:false,configured_at:null}
const previewFlags:Flag[]=[{flag_key:'dentist_ai',description:'Dentist AI review workspace',enabled:true,audience:'professional'},{flag_key:'patient_ai',description:'Patient guidance assistant',enabled:true,audience:'patient'},{flag_key:'experimental_xray_ai',description:'Experimental X-ray observations',enabled:false,audience:'professional'},{flag_key:'sms_notifications',description:'SMS notification delivery',enabled:false,audience:'all'}]
const previewLimits:Limit[]=[{limit_key:'patient_ai_daily',description:'Patient AI requests per day',free_value:5,paid_value:40},{limit_key:'dentist_ai_daily',description:'Dentist AI requests per day',free_value:15,paid_value:150}]

export function AiConfiguration(){
  const[provider,setProvider]=useState(supabase?connectedProvider:previewProvider);const[model,setModel]=useState(supabase?'':previewProvider.model);const[apiKey,setApiKey]=useState('');const[flags,setFlags]=useState(supabase?[]:previewFlags);const[limits,setLimits]=useState(supabase?[]:previewLimits);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null)
  useEffect(()=>{if(!supabase)return;void Promise.all([supabase.from('ai_provider_settings').select('provider,model,key_hint,enabled,configured_at').eq('provider','openai').maybeSingle(),supabase.from('feature_flags').select('*').order('flag_key'),supabase.from('platform_usage_limits').select('*').order('limit_key')]).then(([providerResult,flagResult,limitResult])=>{const error=providerResult.error??flagResult.error??limitResult.error;if(error){setMessage('Live AI configuration could not be loaded. No preview values are being shown.');return}if(providerResult.data){setProvider(providerResult.data as Provider);setModel(providerResult.data.model)}setFlags((flagResult.data??[]) as Flag[]);setLimits((limitResult.data??[]) as Limit[])})},[])
  const rotate=async(event:FormEvent)=>{event.preventDefault();if(apiKey.trim().length<20||model.trim().length<3)return setMessage('Enter the provider model and complete API key.');setBusy('key');setMessage(null);if(!supabase){await new Promise((resolve)=>setTimeout(resolve,250));setProvider({...provider,model,key_hint:`•••• ${apiKey.trim().slice(-4)}`,enabled:true,configured_at:new Date().toISOString()});setApiKey('');setMessage('Preview rotation completed. No credential was stored.');setBusy(null);return}const{data,error}=await supabase.functions.invoke('ai-key-rotate',{body:{provider:'openai',model,apiKey}});setBusy(null);if(error||!data?.ok)return setMessage(data?.error?.code??error?.message??'Key rotation failed.');setProvider({...provider,model,key_hint:data.data.keyHint,enabled:true,configured_at:new Date().toISOString()});setApiKey('');setMessage('Provider credential rotated. The plaintext value cannot be read back.')}
  const toggle=async(flag:Flag)=>{setBusy(flag.flag_key);const error=supabase?(await supabase.rpc('set_feature_flag',{target_key:flag.flag_key,target_enabled:!flag.enabled})).error:null;if(!error)setFlags((current)=>current.map((item)=>item.flag_key===flag.flag_key?{...item,enabled:!item.enabled}:item));setBusy(null);setMessage(error?error.message:'Feature flag updated and audited.')}
  const saveLimit=async(limit:Limit)=>{setBusy(limit.limit_key);const error=supabase?(await supabase.rpc('set_platform_usage_limit',{target_key:limit.limit_key,target_free:limit.free_value,target_paid:limit.paid_value})).error:null;setBusy(null);setMessage(error?error.message:'Usage limit updated and audited.')}
  return<><div className="page-heading config-heading"><div><p className="eyebrow">AI &amp; SAFETY CONTROLS</p><h1>Provider, flags, and limits</h1><p>Turn capabilities on deliberately. Provider keys are write-only and stored encrypted in Supabase Vault.</p></div><div className="config-lock"><ShieldCheck/><span>Super Admin only</span></div></div>{message?<div className="workspace-alert" role="status">{message}</div>:null}
    <div className="ai-config-grid"><section className="panel config-panel"><div className="panel-heading"><div><p className="eyebrow">WRITE-ONLY SECRET</p><h2>AI provider</h2></div><KeyRound/></div><div className="provider-status"><span className={provider.enabled?'status-dot':'status-dot status-dot-off'}/><div><strong>{provider.enabled?'Configured':'Waiting for key'}</strong><small>{provider.model} · {provider.key_hint||'Not configured'}</small></div></div><form className="config-form" onSubmit={rotate}><label>Model<input value={model} onChange={(event)=>setModel(event.target.value)} placeholder="gpt-5-mini"/></label><label>New API key<input type="password" autoComplete="off" value={apiKey} onChange={(event)=>setApiKey(event.target.value)} placeholder="Paste once to rotate"/></label><p>The browser sends the key once to a protected server function. Only its final four characters and rotation time return.</p><Button className="primary-button" type="submit" isPending={busy==='key'}><KeyRound/>Rotate sealed credential</Button></form></section>
      <section className="panel config-panel"><div className="panel-heading"><div><p className="eyebrow">RELEASE CONTROL</p><h2>Feature flags</h2></div><Bot/></div><div className="flag-list">{flags.map((flag)=><article key={flag.flag_key}><div><strong>{flag.description}</strong><small>{flag.audience} · {flag.flag_key}</small></div><button aria-label={`${flag.enabled?'Disable':'Enable'} ${flag.description}`} aria-pressed={flag.enabled} disabled={busy===flag.flag_key} onClick={()=>void toggle(flag)}>{flag.enabled?<ToggleRight/>:<ToggleLeft/>}<span>{flag.enabled?'On':'Off'}</span></button></article>)}</div></section>
    </div><section className="panel quota-panel"><div className="panel-heading"><div><p className="eyebrow">ABUSE PROTECTION</p><h2>Daily usage limits</h2></div><Gauge/></div><div className="quota-grid">{limits.map((limit)=><article key={limit.limit_key}><div><strong>{limit.description}</strong><small>{limit.limit_key}</small></div><label>Free<input type="number" min="0" value={limit.free_value} onChange={(event)=>setLimits((current)=>current.map((item)=>item.limit_key===limit.limit_key?{...item,free_value:Number(event.target.value)}:item))}/></label><label>Paid<input type="number" min={limit.free_value} value={limit.paid_value} onChange={(event)=>setLimits((current)=>current.map((item)=>item.limit_key===limit.limit_key?{...item,paid_value:Number(event.target.value)}:item))}/></label><Button className="secondary-button" isPending={busy===limit.limit_key} onPress={()=>void saveLimit(limit)}><CheckCircle2/>Save</Button></article>)}</div></section></>
}
