import { useEffect, useState, type FormEvent } from 'react'
import { BadgeDollarSign, CheckCircle2, CreditCard, ShieldCheck } from 'lucide-react'
import { Button } from '@heroui/react/button'
import { supabase } from '../lib/supabase'

type Plan={id:string;external_product_id:string;tier:'patient_plus'|'clinic_pro';name_en:string;name_bn:string;price_bdt:number;billing_period:'monthly'|'annual';active:boolean}
const previewPlans:Plan[]=[{id:'1',external_product_id:'patient-plus-monthly',tier:'patient_plus',name_en:'Patient Plus',name_bn:'পেশেন্ট প্লাস',price_bdt:299,billing_period:'monthly',active:true},{id:'2',external_product_id:'clinic-pro-monthly',tier:'clinic_pro',name_en:'Clinic Pro',name_bn:'ক্লিনিক প্রো',price_bdt:2499,billing_period:'monthly',active:true}]
export function FinanceConfiguration(){const[plans,setPlans]=useState<Plan[]>(previewPlans);const[commission,setCommission]=useState('5');const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false)
useEffect(()=>{if(!supabase)return;void supabase.from('subscription_plans').select('id,external_product_id,tier,name_en,name_bn,price_bdt,billing_period,active').order('tier').then(({data})=>{if(data?.length)setPlans(data as Plan[])})},[])
const saveCommission=async(event:FormEvent)=>{event.preventDefault();const rate=Number(commission);if(!Number.isFinite(rate)||rate<0||rate>100)return setMessage('Enter a commission from 0% to 100%.');setBusy(true);const error=supabase?(await supabase.rpc('set_commission_rate',{target_clinic_id:null,rate})).error:null;setBusy(false);setMessage(error?error.message:'Default platform commission saved and audited.')}
return<><div className="page-heading config-heading"><div><p className="eyebrow">REVENUE CONTROLS</p><h1>Plans and commission</h1><p>Configure entitlements without exposing provider credentials to the browser.</p></div><div className="config-lock"><ShieldCheck/><span>Super Admin only</span></div></div>{message?<div className="workspace-alert" role="status">{message}</div>:null}<div className="config-grid"><section className="panel config-panel" aria-labelledby="commission-heading"><div className="panel-heading"><div><p className="eyebrow">PLATFORM</p><h2 id="commission-heading">Default commission</h2></div><BadgeDollarSign/></div><form className="config-form" onSubmit={saveCommission}><label>Rate percent<input aria-label="Rate percent" inputMode="decimal" value={commission} onChange={(event)=>setCommission(event.target.value)}/></label><p>Clinic-specific rules can override this default. New payments capture the active rate in the payable ledger.</p><Button className="primary-button" type="submit" isPending={busy}>Save audited rate</Button></form></section><section className="panel config-panel" aria-labelledby="plans-heading"><div className="panel-heading"><div><p className="eyebrow">REVENUECAT</p><h2 id="plans-heading">Subscription plans</h2></div><CreditCard/></div><div className="plan-list">{plans.map((plan)=><article key={plan.id}><span><CheckCircle2/></span><div><strong>{plan.name_en}</strong><small>{plan.name_bn} · {plan.external_product_id}</small></div><p>৳{Number(plan.price_bdt).toLocaleString()}<small>/{plan.billing_period}</small></p></article>)}</div><p className="config-note">Booking, records, consent, and messaging remain free. Paid tiers unlock only optional quotas and operational tools.</p></section></div></>}
