import { createClient } from 'npm:@supabase/supabase-js@2.112.4'
import { createAiTaskHandler, type AiProvider } from './handler.ts'
const config={supabaseUrl:'https://project.test',publishableKey:'public',serviceRoleKey:'service'};const task='a0000000-0000-4000-8000-000000000001';const patient='a0000000-0000-4000-8000-000000000002'
function assert(value:boolean,message:string){if(!value)throw new Error(message)}
function request(body:unknown,auth=true){return new Request('https://project.test/functions/v1/ai-task',{method:'POST',headers:{'content-type':'application/json',...(auth?{authorization:'Bearer user'}:{})},body:JSON.stringify(body)})}
function factory(audience:'dentist'|'patient'='dentist',auditFails=false){const caller={auth:{getUser:async()=>({data:{user:{id:'user'}},error:null})},rpc:async()=>({data:[{task_id:task,prompt_text:'safe',output_schema:{},context:{},required_fields:audience==='dentist'?['subjective']:[],audience}],error:null})};const service={rpc:async(name:string)=>name==='ai_daily_limit'?{data:audience==='patient'?5:15,error:null}:name==='consume_api_limit'?{data:true,error:null}:name==='ai_provider_secret'?{data:[{model:'model',secret:'secret-value-long-enough'}],error:null}:name==='complete_ai_task'&&auditFails?{data:null,error:{message:'write failed'}}:{data:null,error:null},storage:{from:()=>({download:async()=>({data:null,error:null})})}};return((_u:string,key:string)=>key==='public'?caller:service) as unknown as typeof createClient}
const dentistProvider:AiProvider=async()=>({output:{subjective:'Pain reported',objective:'Not supplied',assessment:'Needs review',plan:'Examine',cautions:[]},requestId:'r1',inputTokens:10,outputTokens:20})
const patientProvider:AiProvider=async()=>({output:{summary:'Your information has been organized.',urgency:'soon',guidance:['Book a dental visit.'],redFlags:['Seek urgent care for breathing difficulty.'],bookingRecommended:true,disclaimer:'This is general information, not a diagnosis or prescription.'},requestId:'r2',inputTokens:10,outputTokens:20})
Deno.test('ai task fails closed without config',async()=>assert((await createAiTaskHandler({})(request({}))).status===503,'503'))
Deno.test('ai task rejects invalid input',async()=>assert((await createAiTaskHandler(config,factory(),dentistProvider)(request({taskType:'bad'}))).status===400,'400'))
Deno.test('dentist receives reviewable draft',async()=>{const response=await createAiTaskHandler(config,factory(),dentistProvider)(request({taskType:'clinical_note',encounterId:patient,input:'Draft from these facts'}));const body=await response.json();assert(response.status===200,'200');assert(body.data.status==='awaiting_review','review')})
Deno.test('patient receives only safe output',async()=>{const response=await createAiTaskHandler(config,factory('patient'),patientProvider)(request({taskType:'symptom_intake',patientProfileId:patient,input:'Pain for two days'}));const body=await response.json();assert(response.status===200,'200');assert(body.data.output.urgency==='soon','safe')})
Deno.test('patient diagnostic output is blocked',async()=>{const unsafe:AiProvider=async()=>({...(await patientProvider({} as never)),output:{summary:'You have an abscess.',urgency:'urgent',guidance:['Book now'],redFlags:[],bookingRecommended:true,disclaimer:'This is general information, not medical advice.'}});assert((await createAiTaskHandler(config,factory('patient'),unsafe)(request({taskType:'symptom_intake',patientProfileId:patient,input:'Pain for two days'}))).status===422,'422')})
Deno.test('Bangla diagnostic and medicine language is blocked',async()=>{const unsafe:AiProvider=async()=>({...(await patientProvider({} as never)),output:{summary:'এটি রোগ নির্ণয়।',urgency:'urgent',guidance:['এই ওষুধ খান।'],redFlags:[],bookingRecommended:true,disclaimer:'এটি শুধু সাধারণ তথ্য, রোগ নির্ণয় বা প্রেসক্রিপশন নয়।'}});assert((await createAiTaskHandler(config,factory('patient'),unsafe)(request({taskType:'symptom_intake',patientProfileId:patient,input:'দুই দিন ধরে দাঁতে ব্যথা',locale:'bn'}))).status===422,'422')})
Deno.test('AI output is withheld when audit persistence fails',async()=>assert((await createAiTaskHandler(config,factory('patient',true),patientProvider)(request({taskType:'symptom_intake',patientProfileId:patient,input:'Pain for two days'}))).status===500,'500'))
