import type { ExpenseInput, InventoryItemInput, LabCaseInput, StockMovementInput } from '@amar-dentist/domain'
import { supabase } from './supabase'
import { getProfessionalOverview } from './phase2'
import { Platform } from 'react-native'

const previewEnabled=process.env.EXPO_PUBLIC_DEMO_MODE==='true';const previewUser='00000000-0000-4000-8000-000000000001';const previewClinic='30000000-0000-4000-8000-000000000001'
export type FinanceSummary={grossPayments:number;refundTotal:number;commissionTotal:number;expenseTotal:number;payoutTotal:number;netPayable:number}
export type InventoryRow={id:string;name:string;sku:string;unit:string;reorderLevel:number;onHand:number;nextExpiry:string|null}
export type LabCaseRow={id:string;caseNumber:string;caseType:string;status:string;dueDate:string;costBdt:number}
export type BusinessContext={clinic:{id:string;name:string}|null;clinics:Array<{id:string;name:string}>;finance:FinanceSummary;inventory:InventoryRow[];labs:LabCaseRow[];subscription:{name:string;status:string;expiresAt:string|null}|null}

const demoContext:BusinessContext={clinic:{id:previewClinic,name:'Shapla Dental Studio'},clinics:[{id:previewClinic,name:'Shapla Dental Studio'}],finance:{grossPayments:48600,refundTotal:1200,commissionTotal:2430,expenseTotal:8900,payoutTotal:22000,netPayable:22970},inventory:[{id:'i1',name:'Examination gloves',sku:'GLV-100',unit:'box',reorderLevel:8,onHand:5,nextExpiry:'2026-11-30'},{id:'i2',name:'Local anaesthetic',sku:'ANE-020',unit:'cartridge',reorderLevel:20,onHand:64,nextExpiry:'2027-03-14'}],labs:[{id:'l1',caseNumber:'LAB-202609-001004',caseType:'Zirconia crown · tooth 16',status:'quality_check',dueDate:'2026-09-07',costBdt:6500},{id:'l2',caseNumber:'LAB-202609-001007',caseType:'Upper retainer',status:'in_progress',dueDate:'2026-09-10',costBdt:2400}],subscription:{name:'Clinic Pro',status:'active',expiresAt:'2026-10-04T00:00:00Z'}}

export async function getBusinessContext(userId:string,selectedClinicId?:string):Promise<BusinessContext>{
  if(!supabase||previewEnabled||userId===previewUser)return demoContext
  const overview=await getProfessionalOverview(userId);const clinic=overview.clinics.find((item)=>item.id===selectedClinicId)??overview.clinics.find((item)=>item.roles.some((role)=>role==='clinic_owner'||role==='clinic_manager'))??null
  if(!clinic)return{...demoContext,clinic:null,clinics:overview.clinics.map(({id,name})=>({id,name})),inventory:[],labs:[],subscription:null,finance:{grossPayments:0,refundTotal:0,commissionTotal:0,expenseTotal:0,payoutTotal:0,netPayable:0}}
  const through=new Date();const from=new Date(through);from.setDate(from.getDate()-30)
  const [financeResult,itemResult,lotResult,labResult,subscriptionResult]=await Promise.all([
    supabase.rpc('clinic_finance_summary',{target_clinic_id:clinic.id,from_date:from.toISOString().slice(0,10),to_date:through.toISOString().slice(0,10)}),
    supabase.from('inventory_items').select('id,name,sku,unit,reorder_level').eq('clinic_id',clinic.id).eq('active',true).order('name'),
    supabase.from('inventory_lots').select('item_id,on_hand,expires_on').gt('on_hand',0).order('expires_on'),
    supabase.from('lab_cases').select('id,case_number,case_type,status,due_date,cost_bdt').eq('clinic_id',clinic.id).order('due_date').limit(20),
    supabase.from('user_subscriptions').select('status,expires_at,subscription_plans(name_en)').eq('clinic_id',clinic.id).in('status',['trialing','active','grace_period']).order('expires_at',{ascending:false}).limit(1).maybeSingle(),
  ])
  const error=financeResult.error??itemResult.error??lotResult.error??labResult.error??subscriptionResult.error;if(error)throw new Error(error.message)
  const financeRow=financeResult.data?.[0]??{};const lots=lotResult.data??[]
  const planRelation=subscriptionResult.data?.subscription_plans as unknown as {name_en:string}|Array<{name_en:string}>|null
  const planName=Array.isArray(planRelation)?planRelation[0]?.name_en:planRelation?.name_en
  return{clinic:{id:clinic.id,name:clinic.name},clinics:overview.clinics.map(({id,name})=>({id,name})),finance:{grossPayments:Number(financeRow.gross_payments??0),refundTotal:Number(financeRow.refund_total??0),commissionTotal:Number(financeRow.commission_total??0),expenseTotal:Number(financeRow.expense_total??0),payoutTotal:Number(financeRow.payout_total??0),netPayable:Number(financeRow.net_payable??0)},inventory:(itemResult.data??[]).map((item)=>{const itemLots=lots.filter((lot)=>lot.item_id===item.id);return{id:item.id,name:item.name,sku:item.sku,unit:item.unit,reorderLevel:Number(item.reorder_level),onHand:itemLots.reduce((sum,lot)=>sum+Number(lot.on_hand),0),nextExpiry:itemLots.map((lot)=>lot.expires_on).filter(Boolean).sort()[0]??null}}),labs:(labResult.data??[]).map((row)=>({id:row.id,caseNumber:row.case_number,caseType:row.case_type,status:row.status,dueDate:row.due_date,costBdt:Number(row.cost_bdt)})),subscription:subscriptionResult.data?{name:planName??'Clinic Pro',status:subscriptionResult.data.status,expiresAt:subscriptionResult.data.expires_at}:null}
}

export async function recordExpense(input:ExpenseInput){if(!supabase||previewEnabled)return;const{error}=await supabase.rpc('record_expense',{target_clinic_id:input.clinicId,expense_category:input.category,expense_description:input.description,amount:input.amountBdt,expense_date:input.incurredOn});if(error)throw new Error(error.message)}
export async function createInventoryItem(input:InventoryItemInput){if(!supabase||previewEnabled)return previewUser;const{data,error}=await supabase.rpc('create_inventory_item',{target_clinic_id:input.clinicId,item_sku:input.sku,item_name:input.name,item_unit:input.unit,reorder:input.reorderLevel});if(error)throw new Error(error.message);return data as string}
export async function postStockMovement(input:StockMovementInput){if(!supabase||previewEnabled)return;const{error}=await supabase.rpc('post_stock_movement',{target_clinic_id:input.clinicId,target_item_id:input.itemId,target_lot_id:input.lotId,movement:input.movementType,movement_quantity:input.quantity,movement_reason:input.reason,source_type:input.referenceType,source_id:input.referenceId});if(error)throw new Error(error.message)}
export async function createLabCase(input:LabCaseInput){if(!supabase||previewEnabled)return previewUser;const{data,error}=await supabase.rpc('create_lab_case',{target_clinic_id:input.clinicId,target_patient_profile_id:input.patientProfileId,target_encounter_id:input.encounterId,target_vendor_id:input.vendorId,target_case_type:input.caseType,target_due_date:input.dueDate,target_cost:input.costBdt,target_notes:input.notes});if(error)throw new Error(error.message);return data as string}

export async function getPatientPayments(userId:string){if(!supabase||previewEnabled||userId===previewUser)return[{id:'p1',appointmentId:'70000000-0000-4000-8000-000000000001',clinicName:'Shapla Dental Studio',amountBdt:500,provider:'bkash',status:'succeeded',createdAt:'2026-09-04T08:30:00Z'}];const{data,error}=await supabase.from('payment_transactions').select('id,appointment_id,amount_bdt,provider,status,created_at,clinics(name)').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((row)=>{const clinicRelation=row.clinics as unknown as{name:string}|Array<{name:string}>|null;return{id:row.id,appointmentId:row.appointment_id,clinicName:(Array.isArray(clinicRelation)?clinicRelation[0]?.name:clinicRelation?.name)??'',amountBdt:Number(row.amount_bdt),provider:row.provider,status:row.status,createdAt:row.created_at}})}
export async function startPaymentCheckout(appointmentId:string,provider:'bkash'|'nagad'){if(!supabase||previewEnabled)return{paymentId:previewUser,checkoutUrl:`https://example.test/${provider}/checkout`,amountBdt:500,currency:'BDT'};const idempotencyKey=`appointment-${appointmentId}-${provider}`;const{data,error}=await supabase.functions.invoke('payment-checkout',{body:{appointmentId,provider,idempotencyKey}});if(error||!data?.ok)throw new Error(data?.error?.code??error?.message??'CHECKOUT_FAILED');return data.data as{paymentId:string;checkoutUrl:string;amountBdt:number;currency:string}}

let purchasesConfigured=false
async function purchases(userId:string){if(Platform.OS==='web')return null;const key=Platform.OS==='ios'?process.env.EXPO_PUBLIC_REVENUECAT_IOS_KEY:process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_KEY;if(!key)return null;const module=await import('react-native-purchases');if(!purchasesConfigured){module.default.configure({apiKey:key,appUserID:userId});purchasesConfigured=true}else await module.default.logIn(userId);return module.default}
export async function getSubscriptionOfferings(userId:string){const client=await purchases(userId);if(!client)return[{identifier:'patient-plus-monthly',title:'Patient Plus',description:'Optional convenience and expanded usage',price:'৳299 / month'}];const offerings=await client.getOfferings();return(offerings.current?.availablePackages??[]).map((item)=>({identifier:item.identifier,title:item.product.title,description:item.product.description,price:item.product.priceString,package:item}))}
export async function purchaseSubscription(userId:string,offer:Awaited<ReturnType<typeof getSubscriptionOfferings>>[number]){const client=await purchases(userId);if(!client||!('package'in offer))throw new Error('SUBSCRIPTIONS_NOT_CONFIGURED');const result=await client.purchasePackage(offer.package);return{active:Object.keys(result.customerInfo.entitlements.active).length>0}}
export async function restoreSubscriptions(userId:string){const client=await purchases(userId);if(!client)return{active:false};const info=await client.restorePurchases();return{active:Object.keys(info.entitlements.active).length>0}}
