import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Redirect, router, Stack } from 'expo-router'
import { CalendarDays, CheckCircle2, Clock3, MessageCircle, ReceiptText, XCircle } from 'lucide-react-native'
import { useState } from 'react'
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native'
import { Button } from '../../src/components/Button'
import { Screen } from '../../src/components/Screen'
import { cancelAppointment, getAppointments } from '../../src/lib/phase3'
import { useAuth } from '../../src/providers/AuthProvider'
import { useLocale } from '../../src/providers/LocaleProvider'
import { colors, radius, spacing } from '../../src/theme'

export default function PatientAppointmentsScreen() {
  const { profile, loading } = useAuth(); const { locale, t } = useLocale(); const queryClient = useQueryClient(); const [busyId, setBusyId] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [cancelledIds, setCancelledIds] = useState<Set<string>>(() => new Set())
  const appointments = useQuery({ queryKey: ['appointments', profile?.id], queryFn: () => getAppointments(profile!.id), enabled: Boolean(profile) })
  if (!loading && !profile) return <Redirect href="/" />; if (!profile) return null
  const formatter = new Intl.DateTimeFormat(locale === 'bn' ? 'bn-BD' : 'en-BD', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Dhaka' })
  const cancel = async (id: string) => { setBusyId(id); setMessage(null); try { const disposition = await cancelAppointment(id, 'Cancelled by patient'); setCancelledIds((items) => new Set(items).add(id)); setMessage(disposition === 'refundable' ? t('depositRefundable') : t('depositForfeited')); await queryClient.invalidateQueries({ queryKey: ['appointments', profile.id] }) } catch { setMessage(t('authUnavailable')) } finally { setBusyId(null) } }
  return <Screen maxWidth={760} style={styles.screen}><Stack.Screen options={{ title: t('appointments'), headerBackTitle: t('back') }} /><View style={styles.heading}><CalendarDays size={28} color={colors.teal} /><View style={styles.headingCopy}><Text style={styles.title}>{t('appointments')}</Text><Text style={styles.subtitle}>{t('appointmentsBody')}</Text></View></View>
    {message ? <View style={styles.notice}><CheckCircle2 size={17} color={colors.teal} /><Text style={styles.noticeText}>{message}</Text></View> : null}
    {appointments.isLoading ? <ActivityIndicator color={colors.teal} /> : appointments.data?.length ? <View style={styles.list}>{appointments.data.map((item) => { const displayStatus = cancelledIds.has(item.id) ? 'cancelled' : item.status; return <View key={item.id} style={styles.card}><View style={styles.cardHeader}><View style={styles.statusIcon}>{displayStatus === 'cancelled' ? <XCircle size={19} color={colors.danger} /> : <CheckCircle2 size={19} color={colors.success} />}</View><View style={styles.cardCopy}><Text style={styles.clinic}>{item.clinicName}</Text><Text style={styles.service}>{item.serviceName}</Text></View><Text style={[styles.status, displayStatus === 'cancelled' && styles.statusCancelled]}>{t(displayStatus === 'confirmed' ? 'statusConfirmed' : displayStatus === 'cancelled' ? 'statusCancelled' : 'statusCompleted')}</Text></View><View style={styles.meta}><Clock3 size={16} color={colors.teal} /><Text style={styles.metaText}>{formatter.format(new Date(item.startAt))}</Text></View><View style={styles.meta}><ReceiptText size={16} color={colors.teal} /><Text style={styles.metaText}>৳{item.depositBdt.toLocaleString()} {t('depositBdt').toLowerCase()}</Text></View><View style={styles.actions}><Pressable accessibilityRole="button" style={styles.chatButton} onPress={() => router.push({ pathname: '/patient/chat', params: { patientProfileId: item.patientProfileId, clinicId: item.clinicId, clinicName: item.clinicName, appointmentId: item.id } })}><MessageCircle size={17} color={colors.teal} /><Text style={styles.chatText}>{t('messageClinic')}</Text></Pressable>{displayStatus === 'confirmed' ? <Button label={t('cancelAppointment')} variant="ghost" loading={busyId === item.id} onPress={() => void cancel(item.id)} /> : null}</View></View> })}</View> : <View style={styles.empty}><CalendarDays size={36} color={colors.teal} /><Text style={styles.emptyTitle}>{t('noAppointments')}</Text><Button label={t('discoverDentists')} onPress={() => router.push('/patient/discover')} /></View>}
  </Screen>
}

const styles = StyleSheet.create({ screen: { paddingTop: spacing.xl, gap: spacing.xl }, heading: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start' }, headingCopy: { flex: 1, gap: 5 }, title: { color: colors.inkDeep, fontSize: 30, fontWeight: '800', letterSpacing: -0.8 }, subtitle: { color: colors.muted, fontSize: 13, lineHeight: 20 }, notice: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.mintSoft }, noticeText: { flex: 1, color: colors.teal, fontSize: 12, lineHeight: 18 }, list: { gap: spacing.md }, card: { gap: spacing.md, padding: spacing.lg, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.paper }, cardHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, statusIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: colors.mintSoft }, cardCopy: { flex: 1, gap: 3 }, clinic: { color: colors.inkDeep, fontSize: 15, fontWeight: '800' }, service: { color: colors.muted, fontSize: 11 }, status: { color: colors.success, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' }, statusCancelled: { color: colors.danger }, meta: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, metaText: { color: colors.ink, fontSize: 12 }, actions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.line, paddingTop: spacing.md }, chatButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.sm }, chatText: { color: colors.teal, fontSize: 12, fontWeight: '800' }, empty: { minHeight: 280, alignItems: 'center', justifyContent: 'center', gap: spacing.lg }, emptyTitle: { color: colors.ink, fontWeight: '800' } })
