// THESIS: A calm triage notebook, not a chatbot theatre. OWN-WORLD: pearl paper, ink, mint, one high-signal urgency card. STORY: choose purpose, describe, receive bounded guidance, book. FIRST VIEWPORT: safety contract plus one input. FORM: quiet care ledger.
import { aiTaskRequestSchema, type PatientGuidance } from '@amar-dentist/domain'
import { useQuery } from '@tanstack/react-query'
import { Redirect, router, Stack } from 'expo-router'
import { AlertTriangle, CalendarPlus2, MessageCircleHeart, ShieldCheck } from 'lucide-react-native'
import { useState } from 'react'
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native'
import { Button } from '../../src/components/Button'
import { Field } from '../../src/components/Field'
import { Screen } from '../../src/components/Screen'
import { SectionCard } from '../../src/components/SectionCard'
import { getPatientProfiles } from '../../src/lib/phase3'
import { getAiFeatureFlags, runAiTask } from '../../src/lib/phase6'
import { useAuth } from '../../src/providers/AuthProvider'
import { useLocale } from '../../src/providers/LocaleProvider'
import { colors, radius, spacing } from '../../src/theme'

type PatientTask='symptom_intake'|'record_explanation'|'general_guidance'
export default function PatientAssistantScreen(){
  const{profile,loading}=useAuth();const{t,locale}=useLocale();const profiles=useQuery({queryKey:['patient-profiles',profile?.id],queryFn:()=>getPatientProfiles(profile!.id),enabled:Boolean(profile)});const flags=useQuery({queryKey:['ai-feature-flags'],queryFn:getAiFeatureFlags,enabled:Boolean(profile)})
  const[taskType,setTaskType]=useState<PatientTask>('symptom_intake');const[input,setInput]=useState('');const[result,setResult]=useState<PatientGuidance|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null)
  if(!loading&&!profile)return<Redirect href="/"/>;if(!profile)return null
  const aiEnabled=flags.data?.patientAi!==false
  const submit=async()=>{if(!aiEnabled)return setMessage(t('aiFeatureDisabled'));const patientProfileId=profiles.data?.[0]?.id;const parsed=aiTaskRequestSchema.safeParse({taskType,patientProfileId,encounterId:null,mediaId:null,input,locale});if(!parsed.success)return setMessage(t('aiDescribeMore'));setBusy(true);setMessage(null);try{const response=await runAiTask(parsed.data);setResult(response.output as PatientGuidance)}catch(error){setMessage(error instanceof Error&&error.message==='AI_PROVIDER_NOT_CONFIGURED'?t('aiNotConfigured'):error instanceof Error&&error.message==='AI_FEATURE_DISABLED'?t('aiFeatureDisabled'):t('aiUnavailable'))}finally{setBusy(false)}}
  const options:[PatientTask,string][]=[['symptom_intake',t('aiSymptoms')],['record_explanation',t('aiExplainRecord')],['general_guidance',t('aiGeneralGuidance')]]
  return<Screen maxWidth={760} style={styles.screen}><Stack.Screen options={{title:t('careAssistant'),headerBackTitle:t('back')}}/>
    <View style={styles.hero}><View style={styles.heroIcon}><MessageCircleHeart size={28} color={colors.mint}/></View><Text style={styles.kicker}>{t('aiPatientEyebrow')}</Text><Text style={styles.title}>{t('careAssistant')}</Text><Text style={styles.subtitle}>{t('aiPatientBody')}</Text></View>
    <View style={styles.safety}><ShieldCheck size={19} color={colors.teal}/><Text style={styles.safetyText}>{t('aiPatientSafety')}</Text></View>
    <View accessibilityRole="tablist" style={styles.tabs}>{options.map(([value,label])=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:taskType===value}} onPress={()=>{setTaskType(value);setResult(null)}} style={[styles.tab,taskType===value&&styles.tabActive]}><Text style={[styles.tabText,taskType===value&&styles.tabTextActive]}>{label}</Text></Pressable>)}</View>
    <SectionCard eyebrow={t('oneClearStep').toUpperCase()} title={taskType==='symptom_intake'?t('aiTellSymptoms'):taskType==='record_explanation'?t('aiChooseRecordPrompt'):t('aiAskGeneral')}><Field label={t('aiYourMessage')} value={input} onChangeText={setInput} editable={aiEnabled} multiline numberOfLines={5} textAlignVertical="top" placeholder={t('aiPromptPlaceholder')} />{!aiEnabled?<Text accessibilityRole="alert" style={styles.error}>{t('aiFeatureDisabled')}</Text>:message?<Text accessibilityRole="alert" style={styles.error}>{message}</Text>:null}<Button label={t('aiGetGuidance')} disabled={!aiEnabled} loading={busy} onPress={()=>void submit()}/></SectionCard>
    {busy?<ActivityIndicator color={colors.teal}/>:null}{result?<View style={styles.result}><View style={[styles.urgency,result.urgency==='emergency'||result.urgency==='urgent'?styles.urgencyHigh:null]}><AlertTriangle size={20} color={result.urgency==='emergency'||result.urgency==='urgent'?colors.danger:colors.teal}/><View style={styles.flex}><Text style={styles.urgencyLabel}>{t('aiUrgency').toUpperCase()} · {result.urgency.toUpperCase()}</Text><Text style={styles.resultSummary}>{result.summary}</Text></View></View><SectionCard title={t('aiNextSteps')}>{result.guidance.map((item,index)=><Text key={`${item}-${index}`} style={styles.bullet}>• {item}</Text>)}{result.redFlags.map((item,index)=><Text key={`${item}-${index}`} style={styles.redFlag}>• {item}</Text>)}<Text style={styles.disclaimer}>{result.disclaimer}</Text>{result.bookingRecommended?<Button label={t('findDentist')} variant="secondary" onPress={()=>router.push('/patient/discover')}/>:null}</SectionCard></View>:null}
    <View style={styles.route}><CalendarPlus2 size={17} color={colors.teal}/><Text style={styles.routeText}>{t('aiBookingRoute')}</Text></View>
  </Screen>
}
const styles=StyleSheet.create({screen:{paddingTop:spacing.xl,gap:spacing.lg},hero:{gap:spacing.sm},heroIcon:{width:54,height:54,borderRadius:27,alignItems:'center',justifyContent:'center',backgroundColor:colors.inkDeep},kicker:{color:colors.teal,fontSize:11,fontWeight:'800',letterSpacing:1.2},title:{color:colors.inkDeep,fontSize:34,lineHeight:39,fontWeight:'800',letterSpacing:-1.1},subtitle:{color:colors.muted,fontSize:14,lineHeight:22},safety:{flexDirection:'row',gap:spacing.sm,padding:spacing.md,backgroundColor:colors.mintSoft,borderRadius:radius.md},safetyText:{flex:1,color:colors.teal,fontSize:12,lineHeight:18},tabs:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},tab:{minHeight:44,justifyContent:'center',paddingHorizontal:14,borderRadius:radius.pill,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line},tabActive:{backgroundColor:colors.inkDeep,borderColor:colors.inkDeep},tabText:{color:colors.text,fontSize:12,fontWeight:'700'},tabTextActive:{color:colors.paper},error:{color:colors.danger,fontSize:12},result:{gap:spacing.lg},urgency:{flexDirection:'row',gap:spacing.md,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.mintSoft},urgencyHigh:{backgroundColor:'#FFF0F0'},urgencyLabel:{color:colors.teal,fontSize:11,fontWeight:'800',letterSpacing:1},resultSummary:{color:colors.inkDeep,fontSize:18,lineHeight:25,fontWeight:'800',marginTop:4},flex:{flex:1},bullet:{color:colors.text,fontSize:14,lineHeight:22},redFlag:{color:colors.danger,fontSize:13,lineHeight:21},disclaimer:{color:colors.muted,fontSize:11,lineHeight:17,fontStyle:'italic'},route:{flexDirection:'row',gap:spacing.sm,paddingHorizontal:spacing.sm,alignItems:'flex-start'},routeText:{flex:1,color:colors.muted,fontSize:11,lineHeight:17}})
