import { useQuery } from '@tanstack/react-query'
import { Redirect, Stack, useLocalSearchParams } from 'expo-router'
import { MessageCircle, Send, ShieldCheck } from 'lucide-react-native'
import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { Screen } from '../../src/components/Screen'
import { getChatMessages, getOrCreateChatThread, sendChatMessage, subscribeToChatMessages, type ChatMessage } from '../../src/lib/phase3'
import { useAuth } from '../../src/providers/AuthProvider'
import { useLocale } from '../../src/providers/LocaleProvider'
import { colors, hitTarget, radius, spacing } from '../../src/theme'

export default function PatientClinicChatScreen() {
  const params = useLocalSearchParams<{ patientProfileId?: string; clinicId?: string; clinicName?: string; appointmentId?: string }>(); const { profile, loading } = useAuth(); const { t } = useLocale(); const [draft, setDraft] = useState(''); const [messages, setMessages] = useState<ChatMessage[]>([]); const [sending, setSending] = useState(false); const [error, setError] = useState<string | null>(null)
  const thread = useQuery({ queryKey: ['chat-thread', params.patientProfileId, params.clinicId, params.appointmentId], queryFn: () => getOrCreateChatThread(params.patientProfileId!, params.clinicId!, params.appointmentId ?? null), enabled: Boolean(profile && params.patientProfileId && params.clinicId) })
  const history = useQuery({ queryKey: ['chat-messages', thread.data], queryFn: () => getChatMessages(thread.data!), enabled: Boolean(thread.data) })
  useEffect(() => { if (history.data) setMessages(history.data) }, [history.data])
  useEffect(() => thread.data ? subscribeToChatMessages(thread.data, (message) => setMessages((items) => items.some((item) => item.id === message.id) ? items : [...items, message])) : undefined, [thread.data])
  if (!loading && !profile) return <Redirect href="/" />; if (!profile) return null
  const send = async () => { if (!thread.data || !draft.trim()) return; const body = draft.trim(); setSending(true); setError(null); try { const id = await sendChatMessage(thread.data, body); setMessages((items) => [...items, { id, senderId: profile.id, body, createdAt: new Date().toISOString() }]); setDraft('') } catch { setError(t('authUnavailable')) } finally { setSending(false) } }
  return <Screen maxWidth={720} style={styles.screen}><Stack.Screen options={{ title: params.clinicName || t('clinicChat'), headerBackTitle: t('back') }} /><View style={styles.heading}><MessageCircle size={26} color={colors.teal} /><View style={styles.headingCopy}><Text style={styles.title}>{params.clinicName || t('clinicChat')}</Text><Text style={styles.subtitle}>{t('clinicChatBody')}</Text></View></View><View style={styles.privacy}><ShieldCheck size={16} color={colors.teal} /><Text style={styles.privacyText}>{t('chatPrivacy')}</Text></View>
    {history.isLoading ? <ActivityIndicator color={colors.teal} /> : <View style={styles.messages}>{messages.map((message) => { const own = message.senderId === profile.id; return <View key={message.id} style={[styles.bubble, own ? styles.bubbleOwn : styles.bubbleClinic]}><Text style={[styles.messageText, own && styles.messageTextOwn]}>{message.body}</Text></View> })}</View>}
    <View style={styles.composer}><TextInput accessibilityLabel={t('messageClinic')} placeholder={t('typeMessage')} placeholderTextColor={colors.muted} multiline value={draft} onChangeText={setDraft} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel={t('sendMessage')} disabled={!draft.trim() || sending} onPress={() => void send()} style={[styles.send, (!draft.trim() || sending) && styles.sendDisabled]}><Send size={19} color={colors.paper} /></Pressable></View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
  </Screen>
}

const styles = StyleSheet.create({ screen: { paddingTop: spacing.xl, gap: spacing.lg }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, headingCopy: { flex: 1, gap: 5 }, title: { color: colors.inkDeep, fontSize: 28, fontWeight: '800', letterSpacing: -0.7 }, subtitle: { color: colors.muted, fontSize: 12, lineHeight: 18 }, privacy: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.mintSoft }, privacyText: { flex: 1, color: colors.teal, fontSize: 11, lineHeight: 17 }, messages: { minHeight: 260, gap: spacing.sm, justifyContent: 'flex-end' }, bubble: { maxWidth: '82%', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.md }, bubbleClinic: { alignSelf: 'flex-start', backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line }, bubbleOwn: { alignSelf: 'flex-end', backgroundColor: colors.ink }, messageText: { color: colors.text, fontSize: 13, lineHeight: 19 }, messageTextOwn: { color: colors.paper }, composer: { minHeight: 56, flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, padding: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.paper }, input: { flex: 1, minHeight: 40, maxHeight: 120, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm, color: colors.text, fontSize: 14 }, send: { width: hitTarget, height: hitTarget, alignItems: 'center', justifyContent: 'center', borderRadius: hitTarget / 2, backgroundColor: colors.ink }, sendDisabled: { opacity: 0.45 }, error: { color: colors.danger, fontSize: 12 } })
