import { useQuery } from '@tanstack/react-query'
import { Redirect, Stack } from 'expo-router'
import { CheckCircle2, Clock3, CreditCard, ReceiptText, RotateCcw, ShieldCheck } from 'lucide-react-native'
import { useState } from 'react'
import { ActivityIndicator, Linking, StyleSheet, Text, View } from 'react-native'
import { Button } from '../../src/components/Button'
import { Screen } from '../../src/components/Screen'
import { SectionCard } from '../../src/components/SectionCard'
import { getAppointments } from '../../src/lib/phase3'
import { getPatientPayments, getSubscriptionOfferings, purchaseSubscription, restoreSubscriptions, startPaymentCheckout } from '../../src/lib/phase5'
import { useAuth } from '../../src/providers/AuthProvider'
import { useLocale } from '../../src/providers/LocaleProvider'
import { colors, radius, spacing } from '../../src/theme'

export default function PatientPaymentsScreen(){const{profile,loading}=useAuth();const{locale,t}=useLocale();const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const payments=useQuery({queryKey:['patient-payments',profile?.id],queryFn:()=>getPatientPayments(profile!.id),enabled:Boolean(profile)});const appointments=useQuery({queryKey:['appointments',profile?.id],queryFn:()=>getAppointments(profile!.id),enabled:Boolean(profile)});const offerings=useQuery({queryKey:['subscription-offerings',profile?.id],queryFn:()=>getSubscriptionOfferings(profile!.id),enabled:Boolean(profile)});if(!loading&&!profile)return<Redirect href="/"/>;if(!profile)return null;const eligible=appointments.data?.find((item)=>item.status==='confirmed');const date=new Intl.DateTimeFormat(locale==='bn'?'bn-BD':'en-BD',{month:'short',day:'numeric',year:'numeric',timeZone:'Asia/Dhaka'});const pay=async(provider:'bkash'|'nagad')=>{if(!eligible)return;setBusy(provider);setMessage(t('paymentRedirect'));try{const result=await startPaymentCheckout(eligible.id,provider);if(result.checkoutUrl.startsWith('https://example.test/'))setMessage(`${provider==='bkash'?'bKash':'Nagad'} · ৳${result.amountBdt.toLocaleString()} · ${t('providerPending')}`);else await Linking.openURL(result.checkoutUrl);await payments.refetch()}catch{setMessage(t('paymentFailed'))}finally{setBusy(null)}};const subscribe=async()=>{const offer=offerings.data?.[0];if(!offer)return;setBusy('subscription');try{const result=await purchaseSubscription(profile.id,offer);setMessage(result.active?t('subscriptionActive'):t('authUnavailable'))}catch{setMessage(t('authUnavailable'))}finally{setBusy(null)}};const restore=async()=>{setBusy('restore');try{const result=await restoreSubscriptions(profile.id);setMessage(result.active?t('subscriptionActive'):t('noSubscriptionRestored'))}catch{setMessage(t('authUnavailable'))}finally{setBusy(null)}}
return<Screen maxWidth={760} style={styles.screen}><Stack.Screen options={{title:t('paymentHistory'),headerBackTitle:t('back')}}/><View style={styles.heading}><CreditCard size={30} color={colors.teal}/><View style={styles.headingCopy}><Text style={styles.title}>{t('paymentHistory')}</Text><Text style={styles.subtitle}>{t('paymentHistoryBody')}</Text></View></View>{message?<View accessibilityRole="alert" style={styles.notice}><ShieldCheck size={18} color={colors.teal}/><Text style={styles.noticeText}>{message}</Text></View>:null}
{eligible?<SectionCard eyebrow={t('trustedPrice').toUpperCase()} title={t('payDeposit')}><View style={styles.paySummary}><View><Text style={styles.clinic}>{eligible.clinicName}</Text><Text style={styles.meta}>{eligible.serviceName}</Text></View><Text style={styles.amount}>৳{eligible.depositBdt.toLocaleString()}</Text></View><Text style={styles.body}>{t('chooseProvider')}</Text><View style={styles.actions}><Button label={t('payWithBkash')} loading={busy==='bkash'} disabled={Boolean(busy)} onPress={()=>void pay('bkash')}/><Button label={t('payWithNagad')} variant="secondary" loading={busy==='nagad'} disabled={Boolean(busy)} onPress={()=>void pay('nagad')}/></View></SectionCard>:null}
<SectionCard eyebrow={t('receipt').toUpperCase()} title={t('paymentHistory')}>{payments.isLoading?<ActivityIndicator color={colors.teal}/>:payments.data?.length?<View>{payments.data.map((payment)=><View key={payment.id} style={styles.row}><View style={styles.icon}>{payment.status==='succeeded'?<CheckCircle2 size={19} color={colors.success}/>:payment.status.includes('refund')?<RotateCcw size={19} color={colors.warning}/>:<Clock3 size={19} color={colors.teal}/>}</View><View style={styles.rowCopy}><Text style={styles.clinic}>{payment.clinicName}</Text><Text style={styles.meta}>{payment.provider==='bkash'?'bKash':'Nagad'} · {date.format(new Date(payment.createdAt))}</Text><Text style={styles.status}>{payment.status==='succeeded'?t('providerSucceeded'):payment.status.includes('refund')?t('providerRefunded'):t('providerPending')}</Text></View><Text style={styles.rowAmount}>৳{payment.amountBdt.toLocaleString()}</Text></View>)}</View>:<View style={styles.empty}><ReceiptText size={32} color={colors.teal}/><Text style={styles.body}>{t('noPayments')}</Text></View>}</SectionCard><SectionCard eyebrow={t('subscription').toUpperCase()} title={t('patientPlus')}><Text style={styles.body}>{t('patientPlusBody')}</Text>{offerings.data?.[0]?<View style={styles.paySummary}><View><Text style={styles.clinic}>{offerings.data[0].title}</Text><Text style={styles.meta}>{offerings.data[0].description}</Text></View><Text style={styles.rowAmount}>{offerings.data[0].price}</Text></View>:null}<View style={styles.actions}><Button label={t('subscribe')} loading={busy==='subscription'} onPress={()=>void subscribe()}/><Button label={t('restorePurchases')} variant="ghost" loading={busy==='restore'} onPress={()=>void restore()}/></View></SectionCard><View style={styles.security}><ShieldCheck size={16} color={colors.teal}/><Text style={styles.body}>{t('essentialFeaturesFree')}</Text></View></Screen>}
const styles=StyleSheet.create({screen:{paddingTop:spacing.xl,gap:spacing.xl},heading:{flexDirection:'row',alignItems:'flex-start',gap:spacing.md},headingCopy:{flex:1,minWidth:0,gap:5},title:{color:colors.inkDeep,fontSize:30,lineHeight:36,fontWeight:'800',letterSpacing:-.8},subtitle:{color:colors.muted,fontSize:13,lineHeight:20},notice:{flexDirection:'row',gap:spacing.sm,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.mintSoft},noticeText:{flex:1,color:colors.teal,fontSize:12,lineHeight:18},paySummary:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:spacing.md},clinic:{color:colors.inkDeep,fontSize:14,fontWeight:'800'},meta:{color:colors.muted,fontSize:11,lineHeight:16},amount:{color:colors.inkDeep,fontSize:26,fontWeight:'800'},body:{color:colors.muted,fontSize:12,lineHeight:18},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:spacing.md,paddingVertical:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},icon:{width:40,height:40,flexShrink:0,alignItems:'center',justifyContent:'center',borderRadius:20,backgroundColor:colors.mintSoft},rowCopy:{flex:1,minWidth:0,gap:3},status:{color:colors.teal,fontSize:10,fontWeight:'800',textTransform:'uppercase'},rowAmount:{color:colors.inkDeep,fontSize:15,fontWeight:'800'},empty:{minHeight:150,alignItems:'center',justifyContent:'center',gap:spacing.md},security:{flexDirection:'row',alignItems:'flex-start',gap:spacing.sm,paddingHorizontal:spacing.sm}})
